# 数据源配置
spring:
  # MySQL数据库
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_shear_plate?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: liuyaowen
    driver-class-name: com.mysql.cj.jdbc.Driver
