# This is a basic workflow to help you get started with Actions

name: Fork Sync

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fork_sync:
    runs-on: ubuntu-latest
    steps: 
      - uses: TobKed/github-forks-sync-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: LiuLiRenM/CloudShearPlate
          target_repository: Glazedman/CloudShearPlate
          upstream_branch: dev
          target_branch: dev
          force: true
          tags: true
    
