# This is a basic workflow to help you get started with Actions

name: Fork Sync

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  schedule:
    - cron: '5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fork_sync:
    runs-on: ubuntu-latest
    steps: 
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: LiuLiRenM
          head: dev
          base: dev
    
