name: synchronise forks

on:
  push:
    branches:
      - master

jobs:
  update_external_airflow_fork:
    runs-on:
      ubuntu-latest
    steps:
      - uses: Glazedman/CloudShearPlate@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: LiuLiRenM/CloudShearPlate
          target_repository: Glazedman/CloudShearPlate
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
